/**
 * Auto-generated generative component manifest
 * DO NOT EDIT — Generated by scripts/component-registry/generative-map-generator.ts
 *
 * Declares which registry components are available in generative UI,
 * how they map to React components, and which need wrappers.
 *
 * Run: pnpm codegen:registry
 */

// =============================================================================
// Direct components — registry components that map 1:1 to Kumo exports
// =============================================================================

export const DIRECT_COMPONENTS = [
  "Badge",
  "Banner",
  "Breadcrumbs",
  "Button",
  "ClipboardText",
  "Cluster",
  "Code",
  "Empty",
  "Field",
  "Flow",
  "Grid",
  "Label",
  "Link",
  "Loader",
  "Meter",
  "Radio",
  "Stack",
  "Table",
  "Text"
] as const;

// =============================================================================
// Sub-component flattening — ParentSub → Parent.Sub in component map
// =============================================================================

export const SUB_COMPONENT_ALIASES = {
  "BreadcrumbsCurrent": {
    "parent": "Breadcrumbs",
    "sub": "Current"
  },
  "BreadcrumbsLink": {
    "parent": "Breadcrumbs",
    "sub": "Link"
  },
  "BreadcrumbsSeparator": {
    "parent": "Breadcrumbs",
    "sub": "Separator"
  },
  "FlowNode": {
    "parent": "Flow",
    "sub": "Node"
  },
  "FlowParallel": {
    "parent": "Flow",
    "sub": "Parallel"
  },
  "RadioGroup": {
    "parent": "Radio",
    "sub": "Group"
  },
  "RadioItem": {
    "parent": "Radio",
    "sub": "Item"
  },
  "SelectOption": {
    "parent": "Select",
    "sub": "Option"
  },
  "TableBody": {
    "parent": "Table",
    "sub": "Body"
  },
  "TableCell": {
    "parent": "Table",
    "sub": "Cell"
  },
  "TableFooter": {
    "parent": "Table",
    "sub": "Footer"
  },
  "TableHead": {
    "parent": "Table",
    "sub": "Head"
  },
  "TableHeader": {
    "parent": "Table",
    "sub": "Header"
  },
  "TableRow": {
    "parent": "Table",
    "sub": "Row"
  }
} as const;

// =============================================================================
// Unified type resolution — generative type → registry component lookup
// =============================================================================

export const TYPE_RESOLUTION_MAP = {
  "BreadcrumbsCurrent": {
    "registryComponent": "Breadcrumbs",
    "subComponent": "Current"
  },
  "BreadcrumbsLink": {
    "registryComponent": "Breadcrumbs",
    "subComponent": "Link"
  },
  "BreadcrumbsSeparator": {
    "registryComponent": "Breadcrumbs",
    "subComponent": "Separator"
  },
  "FlowNode": {
    "registryComponent": "Flow",
    "subComponent": "Node"
  },
  "FlowParallel": {
    "registryComponent": "Flow",
    "subComponent": "Parallel"
  },
  "RadioGroup": {
    "registryComponent": "Radio",
    "subComponent": "Group"
  },
  "RadioItem": {
    "registryComponent": "Radio",
    "subComponent": "Item"
  },
  "SelectOption": {
    "registryComponent": "Select",
    "subComponent": "Option"
  },
  "TableBody": {
    "registryComponent": "Table",
    "subComponent": "Body"
  },
  "TableCell": {
    "registryComponent": "Table",
    "subComponent": "Cell"
  },
  "TableFooter": {
    "registryComponent": "Table",
    "subComponent": "Footer"
  },
  "TableHead": {
    "registryComponent": "Table",
    "subComponent": "Head"
  },
  "TableHeader": {
    "registryComponent": "Table",
    "subComponent": "Header"
  },
  "TableRow": {
    "registryComponent": "Table",
    "subComponent": "Row"
  },
  "Textarea": {
    "registryComponent": "InputArea"
  }
} as const;

// =============================================================================
// Type aliases — LLM output name → Kumo export name
// =============================================================================

export const TYPE_ALIASES = {
  "Textarea": "InputArea"
} as const;

// =============================================================================
// Wrapper targets — components requiring stateful or generative wrappers
// =============================================================================

export const STATEFUL_WRAPPER_TARGETS = [
  "Checkbox",
  "Collapsible",
  "Select",
  "Switch",
  "Tabs"
] as const;

export const GENERATIVE_WRAPPER_TARGETS = [
  "CloudflareLogo",
  "Input",
  "InputArea",
  "Select",
  "Surface"
] as const;

// =============================================================================
// Synthetic types — virtual types not in registry
// =============================================================================

export const SYNTHETIC_TYPES = {
  "Div": "Generic container element rendered as a <div>"
} as const;

// =============================================================================
// All generative types — direct + aliases + sub-components + synthetic
// =============================================================================

export const ALL_GENERATIVE_TYPES = [
  "Badge",
  "Banner",
  "Breadcrumbs",
  "BreadcrumbsCurrent",
  "BreadcrumbsLink",
  "BreadcrumbsSeparator",
  "Button",
  "ClipboardText",
  "Cluster",
  "Code",
  "Div",
  "Empty",
  "Field",
  "Flow",
  "FlowNode",
  "FlowParallel",
  "Grid",
  "Label",
  "Link",
  "Loader",
  "Meter",
  "Radio",
  "RadioGroup",
  "RadioItem",
  "SelectOption",
  "Stack",
  "Table",
  "TableBody",
  "TableCell",
  "TableFooter",
  "TableHead",
  "TableHeader",
  "TableRow",
  "Text",
  "Textarea"
] as const;

// =============================================================================
// Excluded components — intentionally not in generative map
// =============================================================================

export const EXCLUDED_COMPONENTS = {
  "CommandPalette": "Complex overlay with 14 sub-components; requires host keyboard handling",
  "Combobox": "Complex dropdown with search, multi-select, portals; requires host state",
  "DatePicker": "Calendar overlay requires date library and complex state management",
  "DateRangePicker": "Calendar overlay requires date library and complex state management",
  "Dialog": "Portal-based overlay; LLM-generated content should be inline",
  "DropdownMenu": "Portal-based overlay with sub-menus; requires host trigger management",
  "LayerCard": "Specialized dashboard layout component; not suited for freeform generation",
  "MenuBar": "Complex keyboard-navigable menu system; requires host integration",
  "Pagination": "Requires host-managed page state and data fetching",
  "Popover": "Portal-based overlay; LLM-generated content should be inline",
  "SensitiveInput": "Security-sensitive input; should not be auto-generated",
  "Toasty": "Toast notification system requires imperative host API",
  "Tooltip": "Portal-based overlay; requires hover trigger management"
} as const;

// =============================================================================
// Registry snapshot — all component names for drift detection
// =============================================================================

export const REGISTRY_COMPONENT_NAMES = [
  "Badge",
  "Banner",
  "Breadcrumbs",
  "Button",
  "Checkbox",
  "ClipboardText",
  "CloudflareLogo",
  "Cluster",
  "Code",
  "Collapsible",
  "Combobox",
  "CommandPalette",
  "DatePicker",
  "DateRangePicker",
  "Dialog",
  "DropdownMenu",
  "Empty",
  "Field",
  "Flow",
  "Grid",
  "Input",
  "InputArea",
  "Label",
  "LayerCard",
  "Link",
  "Loader",
  "MenuBar",
  "Meter",
  "Pagination",
  "Popover",
  "Radio",
  "Select",
  "SensitiveInput",
  "Stack",
  "Surface",
  "Switch",
  "Table",
  "Tabs",
  "Text",
  "Toasty",
  "Tooltip"
] as const;
