/**
 * CSS Generator for Kumo Themes
 *
 * Generates theme CSS files from the centralized config.
 * Outputs:
 * - theme-kumo.css: Base theme with all tokens
 * - theme-fedramp.css: Override layer for fedramp theme
 * - (future themes as needed)
 */

import { THEME_CONFIG, AVAILABLE_THEMES } from "./config.js";
import type {
  ThemeConfig,
  GeneratorOptions,
  ThemeMetadata,
  ThemeMetadataToken,
  TokenRenameMap,
} from "./types.js";

/**
 * Header comment for generated CSS files
 */
const GENERATED_FILE_HEADER = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by the theme generator.
 * To modify tokens, edit: scripts/theme-generator/config.ts
 * Then run: pnpm codegen:themes
 */

`;

function resolvedTextVariable(name: string): string {
  return `--_text-color-${name}`;
}

function resolvedColorVariable(name: string): string {
  return `--_color-${name}`;
}

function lightTextSlotVariable(name: string): string {
  return `--_text-color-${name}-light`;
}

function darkTextSlotVariable(name: string): string {
  return `--_text-color-${name}-dark`;
}

function lightColorSlotVariable(name: string): string {
  return `--_color-${name}-light`;
}

function darkColorSlotVariable(name: string): string {
  return `--_color-${name}-dark`;
}

function collectThemeEntries(
  config: ThemeConfig,
  themeName: string,
  useNewNames: boolean,
): {
  textEntries: Array<{ name: string; light: string; dark: string }>;
  colorEntries: Array<{ name: string; light: string; dark: string }>;
} {
  const textEntries: Array<{ name: string; light: string; dark: string }> = [];
  const colorEntries: Array<{ name: string; light: string; dark: string }> = [];

  for (const [tokenName, def] of Object.entries(config.text)) {
    const themeColors = def.theme[themeName];
    if (!themeColors) continue;
    const name = useNewNames ? def.newName : tokenName;
    textEntries.push({
      name,
      light: themeColors.light,
      dark: themeColors.dark,
    });
  }

  for (const [tokenName, def] of Object.entries(config.color)) {
    const themeColors = def.theme[themeName];
    if (!themeColors) continue;
    const name = useNewNames ? def.newName : tokenName;
    colorEntries.push({
      name,
      light: themeColors.light,
      dark: themeColors.dark,
    });
  }

  return { textEntries, colorEntries };
}

function pushThemeAliasVariables(
  lines: string[],
  config: ThemeConfig,
  useNewNames: boolean,
): void {
  lines.push(
    "/* Public semantic tokens consumed by Tailwind utilities and consumers.",
  );
  lines.push(
    " * These stay stable while internal vars below handle mode resolution. */",
  );
  lines.push("@theme {");

  for (const [tokenName, def] of Object.entries(config.text)) {
    const name = useNewNames ? def.newName : tokenName;
    lines.push(`  --text-color-${name}: var(${resolvedTextVariable(name)});`);
  }

  lines.push("}");
  lines.push("");
  lines.push("@theme {");

  for (const [tokenName, def] of Object.entries(config.color)) {
    const name = useNewNames ? def.newName : tokenName;
    lines.push(`  --color-${name}: var(${resolvedColorVariable(name)});`);
  }

  lines.push("}");
}

function pushBaseThemeResolvedVariables(
  lines: string[],
  config: ThemeConfig,
  useNewNames: boolean,
): void {
  const { textEntries, colorEntries } = collectThemeEntries(
    config,
    "kumo",
    useNewNames,
  );

  if (textEntries.length === 0 && colorEntries.length === 0) {
    return;
  }

  const lightSelector = ':root, [data-theme="kumo"]';
  const systemDarkSelector = ':root:not([data-mode]), [data-theme="kumo"]';
  const explicitLightSelector =
    '[data-mode="light"]:not([data-theme]), [data-mode="light"] [data-theme="kumo"], [data-theme="kumo"][data-mode="light"]';
  const explicitDarkSelector =
    '[data-mode="dark"]:not([data-theme]), [data-mode="dark"] [data-theme="kumo"], [data-theme="kumo"][data-mode="dark"]';

  const ruleLines: string[] = [];

  ruleLines.push("/* Internal theme plumbing for the base kumo theme.");
  ruleLines.push(
    " * `*-light` / `*-dark` vars store raw values from config.ts once.",
  );
  ruleLines.push(
    " * Resolved vars without the suffix are what public `@theme` tokens read. */",
  );
  ruleLines.push(
    "/* Default light mapping for root and unscoped kumo usage. */",
  );
  ruleLines.push(`${lightSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(`  ${lightTextSlotVariable(entry.name)}: ${entry.light};`);
    ruleLines.push(`  ${darkTextSlotVariable(entry.name)}: ${entry.dark};`);
    ruleLines.push(
      `  ${resolvedTextVariable(entry.name)}: var(${lightTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(`  ${lightColorSlotVariable(entry.name)}: ${entry.light};`);
    ruleLines.push(`  ${darkColorSlotVariable(entry.name)}: ${entry.dark};`);
    ruleLines.push(
      `  ${resolvedColorVariable(entry.name)}: var(${lightColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("}");
  ruleLines.push("");
  ruleLines.push("@media (prefers-color-scheme: dark) {");
  ruleLines.push(
    "  /* System dark mapping when no explicit `data-mode` is set. */",
  );
  ruleLines.push(`  ${systemDarkSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(
      `    ${resolvedTextVariable(entry.name)}: var(${darkTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(
      `    ${resolvedColorVariable(entry.name)}: var(${darkColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("  }");
  ruleLines.push("}");
  ruleLines.push("");
  ruleLines.push(
    "/* Explicit light override, even inside dark parent scopes. */",
  );
  ruleLines.push(`${explicitLightSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(
      `  ${resolvedTextVariable(entry.name)}: var(${lightTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(
      `  ${resolvedColorVariable(entry.name)}: var(${lightColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("}");
  ruleLines.push("");
  ruleLines.push(
    "/* Explicit dark override, even inside light parent scopes. */",
  );
  ruleLines.push(`${explicitDarkSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(
      `  ${resolvedTextVariable(entry.name)}: var(${darkTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(
      `  ${resolvedColorVariable(entry.name)}: var(${darkColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("}");

  lines.push("");
  lines.push("@layer base {");
  for (const line of ruleLines) {
    lines.push(`  ${line}`);
  }
  lines.push("}");
}

function pushOverrideThemeResolvedVariables(
  lines: string[],
  config: ThemeConfig,
  themeName: string,
  useNewNames: boolean,
): void {
  const { textEntries, colorEntries } = collectThemeEntries(
    config,
    themeName,
    useNewNames,
  );

  if (textEntries.length === 0 && colorEntries.length === 0) {
    return;
  }

  const themeSelector = `[data-theme="${themeName}"]`;
  const explicitLightSelector = `[data-mode="light"] ${themeSelector}, ${themeSelector}[data-mode="light"]`;
  const explicitDarkSelector = `[data-mode="dark"] ${themeSelector}, ${themeSelector}[data-mode="dark"]`;
  const ruleLines: string[] = [];

  ruleLines.push(`/* Internal theme plumbing for ${themeName} overrides.`);
  ruleLines.push(
    " * Override themes replace the light/dark slots inside their `data-theme` scope,",
  );
  ruleLines.push(
    " * then reuse the same resolved vars and mode selectors as the base theme. */",
  );
  ruleLines.push(
    `/* Default light mapping for ${themeName} within its data-theme scope. */`,
  );
  ruleLines.push(`${themeSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(`  ${lightTextSlotVariable(entry.name)}: ${entry.light};`);
    ruleLines.push(`  ${darkTextSlotVariable(entry.name)}: ${entry.dark};`);
    ruleLines.push(
      `  ${resolvedTextVariable(entry.name)}: var(${lightTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(`  ${lightColorSlotVariable(entry.name)}: ${entry.light};`);
    ruleLines.push(`  ${darkColorSlotVariable(entry.name)}: ${entry.dark};`);
    ruleLines.push(
      `  ${resolvedColorVariable(entry.name)}: var(${lightColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("}");
  ruleLines.push("");
  ruleLines.push("@media (prefers-color-scheme: dark) {");
  ruleLines.push(
    `  /* System dark mapping for ${themeName} when no explicit mode is set. */`,
  );
  ruleLines.push(`  ${themeSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(
      `    ${resolvedTextVariable(entry.name)}: var(${darkTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(
      `    ${resolvedColorVariable(entry.name)}: var(${darkColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("  }");
  ruleLines.push("}");
  ruleLines.push("");
  ruleLines.push(
    `/* Explicit light override for ${themeName}, even inside dark parent scopes. */`,
  );
  ruleLines.push(`${explicitLightSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(
      `  ${resolvedTextVariable(entry.name)}: var(${lightTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(
      `  ${resolvedColorVariable(entry.name)}: var(${lightColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("}");
  ruleLines.push("");
  ruleLines.push(
    `/* Explicit dark override for ${themeName}, even inside light parent scopes. */`,
  );
  ruleLines.push(`${explicitDarkSelector} {`);
  for (const entry of textEntries) {
    ruleLines.push(
      `  ${resolvedTextVariable(entry.name)}: var(${darkTextSlotVariable(entry.name)});`,
    );
  }
  for (const entry of colorEntries) {
    ruleLines.push(
      `  ${resolvedColorVariable(entry.name)}: var(${darkColorSlotVariable(entry.name)});`,
    );
  }
  ruleLines.push("}");

  lines.push("@layer base {");
  for (const line of ruleLines) {
    lines.push(`  ${line}`);
  }
  lines.push("}");
}

/**
 * Generate the base kumo theme CSS
 * This contains all tokens with their kumo theme values
 */
export function generateKumoThemeCSS(
  config: ThemeConfig,
  useNewNames = false,
): string {
  const lines: string[] = [GENERATED_FILE_HEADER];

  pushThemeAliasVariables(lines, config, useNewNames);

  // Typography tokens (font sizes and line heights)
  if (config.typography && Object.keys(config.typography).length > 0) {
    lines.push("");
    lines.push("@theme {");
    lines.push("  /* Typography - text sizes and line heights */");

    for (const [tokenName, def] of Object.entries(config.typography)) {
      const name = useNewNames && def.newName ? def.newName : tokenName;
      const value = def.theme.kumo;

      lines.push(`  --text-${name}: ${value};`);
    }

    lines.push("}");
  }

  // Explicit runtime vars avoid transient unresolved light-dark() values
  // during class/DOM mutations in some browser style recalculation paths.
  pushBaseThemeResolvedVariables(lines, config, useNewNames);

  return lines.join("\n");
}

/**
 * Generate a theme override CSS file
 * Only includes tokens that differ from the base kumo theme
 */
export function generateThemeOverrideCSS(
  config: ThemeConfig,
  themeName: string,
  useNewNames = false,
): string {
  if (themeName === "kumo") {
    throw new Error("Use generateKumoThemeCSS for the base kumo theme");
  }

  const lines = [GENERATED_FILE_HEADER];
  const typographyOverrides: string[] = [];

  if (config.typography) {
    for (const [tokenName, def] of Object.entries(config.typography)) {
      const themeValue = def.theme[themeName];
      if (themeValue) {
        const name = useNewNames && def.newName ? def.newName : tokenName;
        typographyOverrides.push(`    --text-${name}: ${themeValue};`);
      }
    }
  }

  const { textEntries, colorEntries } = collectThemeEntries(
    config,
    themeName,
    useNewNames,
  );

  if (
    typographyOverrides.length === 0 &&
    textEntries.length === 0 &&
    colorEntries.length === 0
  ) {
    return `${GENERATED_FILE_HEADER}/* No overrides for ${themeName} theme */\n`;
  }

  if (typographyOverrides.length > 0) {
    lines.push("@layer base {");
    lines.push(`  [data-theme="${themeName}"] {`);
    lines.push(...typographyOverrides);
    lines.push("  }");
    lines.push("}");
  }

  pushOverrideThemeResolvedVariables(lines, config, themeName, useNewNames);

  return `${lines.join("\n")}\n`;
}

/**
 * Get a mapping of old token names to new names
 * Useful for running codemods during migration
 */
export function getTokenRenameMap(config: ThemeConfig): TokenRenameMap {
  const textMap: Record<string, string> = {};
  const colorMap: Record<string, string> = {};

  for (const [tokenName, def] of Object.entries(config.text)) {
    textMap[tokenName] = def.newName;
  }

  for (const [tokenName, def] of Object.entries(config.color)) {
    colorMap[tokenName] = def.newName;
  }

  return { text: textMap, color: colorMap };
}

/**
 * Generate all theme CSS files
 */
export function generateAllThemes(
  options: GeneratorOptions,
): Map<string, string> {
  const { useNewNames = false, themes = [...AVAILABLE_THEMES] } = options;
  const files = new Map<string, string>();

  // Always generate base kumo theme
  if (themes.includes("kumo")) {
    files.set(
      "theme-kumo.css",
      generateKumoThemeCSS(THEME_CONFIG, useNewNames),
    );
  }

  // Generate override themes
  for (const themeName of themes) {
    if (themeName !== "kumo") {
      files.set(
        `theme-${themeName}.css`,
        generateThemeOverrideCSS(THEME_CONFIG, themeName, useNewNames),
      );
    }
  }

  return files;
}

function buildMetadataToken(input: {
  tokenName: string;
  cssVariable: string;
  tailwindUtilityFamily: ThemeMetadataToken["tailwindUtilityFamily"];
  kind: ThemeMetadataToken["kind"];
  newName: string;
  description?: string;
  themes: Record<string, { light: string; dark: string } | string>;
}): ThemeMetadataToken {
  return {
    name: input.tokenName,
    cssVariable: input.cssVariable,
    tailwindUtilityFamily: input.tailwindUtilityFamily,
    kind: input.kind,
    defaultTheme: "kumo",
    newName: input.newName,
    ...(input.description !== undefined
      ? { description: input.description }
      : {}),
    themes: input.themes,
  };
}

function compactThemeValues(
  themes: Record<string, { light: string; dark: string } | string | undefined>,
): Record<string, { light: string; dark: string } | string> {
  const entries: Record<string, { light: string; dark: string } | string> = {};

  for (const [themeName, value] of Object.entries(themes)) {
    if (value !== undefined) {
      entries[themeName] = value;
    }
  }

  return entries;
}

export function generateThemeMetadata(config: ThemeConfig): ThemeMetadata {
  const tokens: ThemeMetadataToken[] = [];

  for (const [tokenName, def] of Object.entries(config.text)) {
    tokens.push(
      buildMetadataToken({
        tokenName,
        cssVariable: `--text-color-${tokenName}`,
        tailwindUtilityFamily: "text",
        kind: "text",
        newName: def.newName,
        description: def.description,
        themes: compactThemeValues({ ...def.theme }),
      }),
    );
  }

  for (const [tokenName, def] of Object.entries(config.color)) {
    tokens.push(
      buildMetadataToken({
        tokenName,
        cssVariable: `--color-${tokenName}`,
        tailwindUtilityFamily: "bg-border-ring",
        kind: "color",
        newName: def.newName,
        description: def.description,
        themes: compactThemeValues({ ...def.theme }),
      }),
    );
  }

  if (config.typography) {
    for (const [tokenName, def] of Object.entries(config.typography)) {
      tokens.push(
        buildMetadataToken({
          tokenName,
          cssVariable: `--text-${tokenName}`,
          tailwindUtilityFamily: "typography",
          kind: "typography",
          newName: def.newName,
          description: def.description,
          themes: compactThemeValues({ ...def.theme }),
        }),
      );
    }
  }

  return {
    themes: [...AVAILABLE_THEMES],
    tokens,
  };
}

/**
 * List all tokens with their current and new names
 * Useful for documentation and migration planning
 */
export function listAllTokens(config: ThemeConfig): Array<{
  type: "text" | "color" | "typography";
  currentName: string;
  newName: string;
  themes: string[];
}> {
  const tokens: Array<{
    type: "text" | "color" | "typography";
    currentName: string;
    newName: string;
    themes: string[];
  }> = [];

  for (const [tokenName, def] of Object.entries(config.text)) {
    tokens.push({
      type: "text",
      currentName: tokenName,
      newName: def.newName,
      themes: Object.keys(def.theme),
    });
  }

  for (const [tokenName, def] of Object.entries(config.color)) {
    tokens.push({
      type: "color",
      currentName: tokenName,
      newName: def.newName,
      themes: Object.keys(def.theme),
    });
  }

  if (config.typography) {
    for (const [tokenName, def] of Object.entries(config.typography)) {
      tokens.push({
        type: "typography",
        currentName: tokenName,
        newName: def.newName,
        themes: Object.keys(def.theme),
      });
    }
  }

  return tokens;
}
