export {
  Dialog,
  DialogRoot,
  DialogTrigger,
  DialogContent,
  DialogTitle,
  DialogDescription,
  DialogClose,
  DialogBody,
  DialogFooter,
  DialogSeparator,
  type DialogProps,
  type DialogContentProps,
  type DialogRootProps,
  type DialogTriggerProps,
  type DialogTitleProps,
  type DialogDescriptionProps,
  type DialogCloseProps,
  type DialogBodyProps,
  type DialogFooterProps,
  type DialogSeparatorProps,
} from "./dialog";
