/**
 * Auto-generated Zod schemas for Kumo components
 * DO NOT EDIT - Generated by scripts/component-registry/index.ts
 *
 * These schemas enable runtime validation of AI-generated UI trees.
 *
 * NOTE: This is a STUB file for fresh clones. Run `pnpm codegen:registry`
 * to generate the full schema definitions from component source files.
 */

import { z } from "zod";

// SafeParseReturnType was removed in Zod v4, but we still want stable typing.
export type SafeParseResult<T> =
  | { success: true; data: T; error?: never }
  | { success: false; error: z.ZodError<any>; data?: never };

// =============================================================================
// Dynamic Value Schema (for data binding)
// =============================================================================

/**
 * A value that can either be a literal or a reference to the data model.
 * Example: "Hello" or { path: "/user/name" }
 */
export const DynamicValueSchema = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.null(),
  z.object({ path: z.string() }),
]);

export type DynamicValue<T = unknown> = T | { path: string };

// =============================================================================
// Visibility Condition Schemas
// =============================================================================

/**
 * Visibility conditions for conditional rendering.
 * Components can be shown/hidden based on data, auth, or logic expressions.
 */

// Forward declaration for recursive types
export type LogicExpression =
  | { and: LogicExpression[] }
  | { or: LogicExpression[] }
  | { not: LogicExpression }
  | { path: string }
  | { eq: [DynamicValue, DynamicValue] }
  | { neq: [DynamicValue, DynamicValue] }
  | { gt: [DynamicValue, DynamicValue] }
  | { gte: [DynamicValue, DynamicValue] }
  | { lt: [DynamicValue, DynamicValue] }
  | { lte: [DynamicValue, DynamicValue] };

// Lazy schema for recursive logic expressions
const LogicExpressionSchema: z.ZodType<LogicExpression> = z.lazy(() =>
  z.union([
    z.object({ and: z.array(LogicExpressionSchema) }),
    z.object({ or: z.array(LogicExpressionSchema) }),
    z.object({ not: LogicExpressionSchema }),
    z.object({ path: z.string() }),
    z.object({ eq: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ neq: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ gt: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ gte: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ lt: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ lte: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
  ]),
);

export const VisibilityConditionSchema = z.union([
  z.boolean(),
  z.object({ path: z.string() }),
  z.object({ auth: z.enum(["signedIn", "signedOut"]) }),
  LogicExpressionSchema,
]);

export type VisibilityCondition = z.infer<typeof VisibilityConditionSchema>;

// =============================================================================
// Action Schemas
// =============================================================================

export const ActionConfirmSchema = z.object({
  title: z.string(),
  message: z.string(),
  variant: z.enum(["default", "danger"]).optional(),
  confirmLabel: z.string().optional(),
  cancelLabel: z.string().optional(),
});

export const ActionSchema = z.object({
  name: z.string(),
  params: z.record(z.string(), DynamicValueSchema).optional(),
  confirm: ActionConfirmSchema.optional(),
  onSuccess: z
    .object({ set: z.record(z.string(), DynamicValueSchema) })
    .optional(),
  onError: z
    .object({ set: z.record(z.string(), DynamicValueSchema) })
    .optional(),
});

export type Action = z.infer<typeof ActionSchema>;

// =============================================================================
// Component Props Schemas (STUB)
// =============================================================================

/**
 * STUB: Component props schemas will be generated here when running
 * `pnpm codegen:registry`. This stub provides basic structure for
 * TypeScript to compile without full component definitions.
 */
export const ComponentPropsSchemas = {} as const;

// =============================================================================
// Component Type Union (STUB)
// =============================================================================

export type KumoComponentType = never;

export const KumoComponentTypeSchema = z.enum(["placeholder"] as [
  string,
  ...string[],
]);

// =============================================================================
// UI Element & Tree Schemas
// =============================================================================

export const UIElementBaseSchema = z.object({
  key: z.string(),
  type: z.string(), // Relaxed from KumoComponentTypeSchema for stub
  props: z.record(z.string(), z.unknown()),
  children: z.array(z.string()).optional(),
  parentKey: z.string().nullable().optional(),
  visible: VisibilityConditionSchema.optional(),
  action: ActionSchema.optional(),
});

export type UIElement = z.infer<typeof UIElementBaseSchema>;

export const UITreeSchema = z.object({
  root: z.string(),
  elements: z.record(z.string(), UIElementBaseSchema),
});

export type UITree = z.infer<typeof UITreeSchema>;

// =============================================================================
// Validation Helpers
// =============================================================================

export function validateElementProps(
  element: UIElement,
): SafeParseResult<unknown> {
  return {
    success: false,
    error: new z.ZodError([
      {
        code: "custom",
        message:
          "Schema not generated. Run `pnpm codegen:registry` to generate full schemas.",
        path: ["type"],
      },
    ]),
  };
}

export function validateUITree(tree: unknown): SafeParseResult<UITree> {
  return UITreeSchema.safeParse(tree);
}

// =============================================================================
// Component Names (STUB)
// =============================================================================

export const KUMO_COMPONENT_NAMES: readonly string[] = [];
