#!/usr/bin/env npx tsx
/**
 * Extract Skills from SKILL.md files
 *
 * Reads all SKILL.md files from src/skills/ and generates a TypeScript
 * module with metadata + content for playground skill injection.
 *
 * Run: pnpm codegen:skills
 * Output: src/lib/skills-data.generated.ts
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const skillsDir = join(__dirname, "../src/skills");
const outputPath = join(__dirname, "../src/lib/skills-data.generated.ts");

interface SkillEntry {
  /** Directory name used as stable ID */
  id: string;
  /** Human-readable name from frontmatter */
  name: string;
  /** Short description from frontmatter */
  description: string;
  /** Full markdown content (after frontmatter) for prompt injection */
  content: string;
}

/**
 * Parse YAML-ish frontmatter from a SKILL.md file.
 * Only extracts `name` and `description` — not a full YAML parser.
 */
function parseFrontmatter(raw: string): {
  name: string;
  description: string;
  body: string;
} {
  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!fmMatch) {
    return { name: "", description: "", body: raw };
  }

  const fm = fmMatch[1];
  const body = raw.slice(fmMatch[0].length).trim();

  // Extract name
  const nameMatch = fm.match(/^name:\s*(.+)$/m);
  const name = nameMatch ? nameMatch[1].trim() : "";

  // Extract description — may be single-line or multi-line (folded YAML >)
  let description = "";
  const descSingleMatch = fm.match(
    /^description:\s*(?:["'](.+?)["']|(?!>)(.+))$/m,
  );
  const descMultiMatch = fm.match(
    /^description:\s*>\s*\n([\s\S]*?)(?=\n\w|$)/m,
  );

  if (descSingleMatch) {
    description = (descSingleMatch[1] ?? descSingleMatch[2] ?? "").trim();
  } else if (descMultiMatch) {
    description = descMultiMatch[1]
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean)
      .join(" ");
  }

  return { name, description, body };
}

function main() {
  const dirs = readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const skills: SkillEntry[] = [];

  for (const dir of dirs) {
    const skillPath = join(skillsDir, dir, "SKILL.md");
    if (!existsSync(skillPath)) continue;

    const raw = readFileSync(skillPath, "utf-8");
    const { name, description, body } = parseFrontmatter(raw);

    if (!name) {
      console.warn(`[skills] Skipping ${dir}: no name in frontmatter`);
      continue;
    }

    skills.push({
      id: dir,
      name,
      description: description || name,
      content: body,
    });
  }

  console.log(
    `[skills] Extracted ${skills.length} skills from ${dirs.length} directories`,
  );

  const output = `// AUTO-GENERATED by scripts/extract-skills.ts — do not edit manually.

/**
 * Skill metadata for the playground UI (lightweight — no content).
 */
export interface SkillMeta {
  readonly id: string;
  readonly name: string;
  readonly description: string;
}

/**
 * Full skill entry with content for system prompt injection.
 */
export interface SkillEntry extends SkillMeta {
  readonly content: string;
}

/**
 * All extracted skills with full content.
 */
export const SKILLS: readonly SkillEntry[] = ${JSON.stringify(skills, null, 2)} as const;

/**
 * Lightweight metadata-only list for the client UI.
 */
export const SKILL_META: readonly SkillMeta[] = SKILLS.map(({ id, name, description }) => ({
  id,
  name,
  description,
}));

/**
 * Look up a skill by ID. Returns undefined if not found.
 */
export function getSkillById(id: string): SkillEntry | undefined {
  return SKILLS.find((s) => s.id === id);
}

/**
 * Get full content for multiple skill IDs (for system prompt injection).
 */
export function getSkillContents(ids: readonly string[]): string {
  const idSet = new Set(ids);
  return SKILLS
    .filter((s) => idSet.has(s.id))
    .map((s) => \`## Skill: \${s.name}\\n\\n\${s.content}\`)
    .join("\\n\\n---\\n\\n");
}
`;

  writeFileSync(outputPath, output, "utf-8");
  console.log(`[skills] Wrote ${outputPath}`);
}

main();
